owner: tussanakorn
git-repo: kube-pod-alerts
charts-repo-url: https://tussanakorn.github.io/kube-pod-alerts
pages-branch: gh-pages
package-path: .cr-release-packages
index-path: .
release-name-template: "{{ .Name }}-{{ .Version }}"
