apiVersion: v2
name: kube-pod-alerts
description: Kubernetes pod failure monitor that sends Microsoft Teams alerts
type: application
version: 0.1.4
appVersion: "1.0.2"
home: https://github.com/tussanakorn/kube-pod-alerts
sources:
  - https://github.com/tussanakorn/kube-pod-alerts
keywords:
  - kubernetes
  - pods
  - alerting
  - microsoft-teams
  - monitoring
maintainers:
  - name: Tussanakorn Rat
annotations:
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
